# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj2ui.ui'
#
# Created: Thu Apr 24 22:51:05 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainembext = QtGui.QTabWidget(self.centralwidget)
        self.mainembext.setGeometry(QtCore.QRect(20, 290, 361, 261))
        self.mainembext.setAutoFillBackground(False)
        self.mainembext.setObjectName("mainembext")
        self.extract = QtGui.QWidget()
        self.extract.setObjectName("extract")
        self.label_3 = QtGui.QLabel(self.extract)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.embsource = QtGui.QLineEdit(self.extract)
        self.embsource.setGeometry(QtCore.QRect(190, 10, 141, 20))
        self.embsource.setObjectName("embsource")
        self.label_4 = QtGui.QLabel(self.extract)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.embscan = QtGui.QComboBox(self.extract)
        self.embscan.setGeometry(QtCore.QRect(190, 40, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.embscan.setFont(font)
        self.embscan.setEditable(False)
        self.embscan.setObjectName("embscan")
        self.embscan.addItem("")
        self.embscan.addItem("")
        self.embencyes = QtGui.QRadioButton(self.extract)
        self.embencyes.setGeometry(QtCore.QRect(40, 90, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.embencyes.setFont(font)
        self.embencyes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.embencyes.setObjectName("embencyes")
        self.label_8 = QtGui.QLabel(self.extract)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.embkey = QtGui.QLineEdit(self.extract)
        self.embkey.setGeometry(QtCore.QRect(240, 90, 113, 20))
        self.embkey.setObjectName("embkey")
        self.embencno = QtGui.QRadioButton(self.extract)
        self.embencno.setGeometry(QtCore.QRect(40, 110, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.embencno.setFont(font)
        self.embencno.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.embencno.setObjectName("embencno")
        self.label_16 = QtGui.QLabel(self.extract)
        self.label_16.setGeometry(QtCore.QRect(190, 90, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtGui.QLabel(self.extract)
        self.label_17.setGeometry(QtCore.QRect(10, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.embtarget = QtGui.QLineEdit(self.extract)
        self.embtarget.setGeometry(QtCore.QRect(190, 140, 141, 20))
        self.embtarget.setObjectName("embtarget")
        self.embpush = QtGui.QPushButton(self.extract)
        self.embpush.setGeometry(QtCore.QRect(60, 190, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        self.embpush.setFont(font)
        self.embpush.setObjectName("embpush")
        self.mainembext.addTab(self.extract, "")
        self.embed = QtGui.QWidget()
        self.embed.setObjectName("embed")
        self.label_5 = QtGui.QLabel(self.embed)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.extscan = QtGui.QComboBox(self.embed)
        self.extscan.setGeometry(QtCore.QRect(180, 40, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.extscan.setFont(font)
        self.extscan.setEditable(False)
        self.extscan.setObjectName("extscan")
        self.extscan.addItem("")
        self.extscan.addItem("")
        self.extencyes = QtGui.QRadioButton(self.embed)
        self.extencyes.setGeometry(QtCore.QRect(40, 100, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.extencyes.setFont(font)
        self.extencyes.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.extencyes.setObjectName("extencyes")
        self.label_6 = QtGui.QLabel(self.embed)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.extencno = QtGui.QRadioButton(self.embed)
        self.extencno.setGeometry(QtCore.QRect(40, 120, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.extencno.setFont(font)
        self.extencno.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.extencno.setObjectName("extencno")
        self.label_7 = QtGui.QLabel(self.embed)
        self.label_7.setGeometry(QtCore.QRect(180, 100, 46, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.extkey = QtGui.QLineEdit(self.embed)
        self.extkey.setGeometry(QtCore.QRect(230, 100, 113, 20))
        self.extkey.setObjectName("extkey")
        self.label_27 = QtGui.QLabel(self.embed)
        self.label_27.setGeometry(QtCore.QRect(10, 150, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.exttarget = QtGui.QLineEdit(self.embed)
        self.exttarget.setGeometry(QtCore.QRect(162, 150, 171, 20))
        self.exttarget.setObjectName("exttarget")
        self.label_28 = QtGui.QLabel(self.embed)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.extmsgtyp = QtGui.QComboBox(self.embed)
        self.extmsgtyp.setGeometry(QtCore.QRect(180, 10, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.extmsgtyp.setFont(font)
        self.extmsgtyp.setEditable(False)
        self.extmsgtyp.setObjectName("extmsgtyp")
        self.extmsgtyp.addItem("")
        self.extmsgtyp.addItem("")
        self.extpush = QtGui.QPushButton(self.embed)
        self.extpush.setGeometry(QtCore.QRect(60, 200, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(14)
        self.extpush.setFont(font)
        self.extpush.setObjectName("extpush")
        self.mainembext.addTab(self.embed, "")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.successdisp = QtGui.QLabel(self.centralwidget)
        self.successdisp.setGeometry(QtCore.QRect(360, 50, 151, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.successdisp.setFont(font)
        self.successdisp.setObjectName("successdisp")
        self.medpath = QtGui.QLineEdit(self.centralwidget)
        self.medpath.setGeometry(QtCore.QRect(110, 260, 191, 20))
        self.medpath.setObjectName("medpath")
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(20, 260, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 40, 321, 211))
        self.graphicsView.setObjectName("graphicsView")
        self.load = QtGui.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(320, 260, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load.setFont(font)
        self.load.setObjectName("load")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.mainembext.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Source File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Scanning Direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.embscan.setItemText(0, QtGui.QApplication.translate("MainWindow", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.embscan.setItemText(1, QtGui.QApplication.translate("MainWindow", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.embencyes.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Apply Encryption?", None, QtGui.QApplication.UnicodeUTF8))
        self.embencno.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Target File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.embpush.setText(QtGui.QApplication.translate("MainWindow", "Embed Message", None, QtGui.QApplication.UnicodeUTF8))
        self.mainembext.setTabText(self.mainembext.indexOf(self.extract), QtGui.QApplication.translate("MainWindow", "Embed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Scanning Direction:", None, QtGui.QApplication.UnicodeUTF8))
        self.extscan.setItemText(0, QtGui.QApplication.translate("MainWindow", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.extscan.setItemText(1, QtGui.QApplication.translate("MainWindow", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.extencyes.setText(QtGui.QApplication.translate("MainWindow", "Yes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Apply Encryption?", None, QtGui.QApplication.UnicodeUTF8))
        self.extencno.setText(QtGui.QApplication.translate("MainWindow", "No", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Target File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Message Type", None, QtGui.QApplication.UnicodeUTF8))
        self.extmsgtyp.setItemText(0, QtGui.QApplication.translate("MainWindow", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.extmsgtyp.setItemText(1, QtGui.QApplication.translate("MainWindow", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.extpush.setText(QtGui.QApplication.translate("MainWindow", "Extract Message", None, QtGui.QApplication.UnicodeUTF8))
        self.mainembext.setTabText(self.mainembext.indexOf(self.embed), QtGui.QApplication.translate("MainWindow", "Extract", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Stego-Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.successdisp.setText(QtGui.QApplication.translate("MainWindow", "Image Success: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Medium Path", None, QtGui.QApplication.UnicodeUTF8))
        self.load.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

